#**Importing libraries and the data**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from google.colab import files
import io

In [ ]:
upload=files.upload()

Saving nfl_draft.csv to nfl_draft.csv

In [ ]:
nfl_draft = pd.read_csv(io.BytesIO(upload["nfl_draft.csv"]))

# 1. **EDA - Exploratory Data Analysis**

In [ ]:
nfl_draft.head()

,Year,Player,Age,School,Height,Weight,Sprint_40yd,Vertical_Jump,Bench_Press_Reps,Broad_Jump,Agility_3cone,Shuttle,Drafted..tm.rnd.yr.,BMI,Player_Type,Position_Type,Position,Drafted
0,2009,Beanie Wells\WellCh00,20.0,Ohio St.,1.8542,106.594207,4.38,85.09,25.0,325.12,NaN,NaN,Arizona Cardinals / 1st / 31st pick / 2009,31.004194,offense,backs_receivers,RB,Yes
1,2009,Will Davis\DaviWi99,22.0,Illinois,1.8796,118.387609,4.84,83.82,27.0,292.10,7.38,4.45,Arizona Cardinals / 6th / 204th pick / 2009,33.510073,defense,defensive_lineman,DE,Yes
2,2009,Herman Johnson\JohnHe23,24.0,LSU,2.0066,165.107623,5.50,NaN,21.0,NaN,NaN,NaN,Arizona Cardinals / 5th / 167th pick / 2009,41.005821,offense,offensive_lineman,OG,Yes
3,2009,Rashad Johnson\JohnRa98,23.0,Alabama,1.8034,92.079251,4.49,93.98,15.0,304.80,7.09,4.23,Arizona Cardinals / 3rd / 95th pick / 2009,28.312463,defense,defensive_back,FS,Yes
4,2009,Cody Brown\BrowCo96,22.0,Connecticut,1.8796,110.676538,4.76,92.71,26.0,304.80,7.10,4.40,Arizona Cardinals / 2nd / 63rd pick / 2009,31.327425,defense,line_backer,OLB,Yes

We are going to see what features we have for these football players. They are 'Year', 'Player', 'Age', 'School', 'Height', 'Weight', 'Sprint_40yd', 'Vertical_Jump', 'Bench_Press_Reps', 'Broad_Jump', 'Agility_3cone','Shuttle', 'Drafted..tm.rnd.yr.', 'BMI', 'Player_Type', 'Position_Type', 'Position',. The target will be if the player is drafted or not - 'Drafted'

In [ ]:
nfl_draft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3477 entries, 0 to 3476
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 3477 non-null   int64
 1   Player               3477 non-null   object
 2   Age                  2927 non-null   float64
 3   School               3477 non-null   object
 4   Height               3477 non-null   float64
 5   Weight               3477 non-null   float64
 6   Sprint_40yd          3303 non-null   float64
 7   Vertical_Jump        2780 non-null   float64
 8   Bench_Press_Reps     2572 non-null   float64
 9   Broad_Jump           2749 non-null   float64
 10  Agility_3cone        2260 non-null   float64
 11  Shuttle              2337 non-null   float64
 12  Drafted..tm.rnd.yr.  2254 non-null   object
 13  BMI                  3477 non-null   float64
 14  Player_Type          3477 non-null   object
 15  Position_Type        3477 non-null   object
 16  Position             3477 non-null   object
 17  Drafted              3477 non-null   object
dtypes: float64(10), int64(1), object(7)
memory usage: 489.1+ KB

In [ ]:
nfl_draft.columns

Index(['Year', 'Player', 'Age', 'School', 'Height', 'Weight', 'Sprint_40yd',
       'Vertical_Jump', 'Bench_Press_Reps', 'Broad_Jump', 'Agility_3cone',
       'Shuttle', 'Drafted..tm.rnd.yr.', 'BMI', 'Player_Type', 'Position_Type',
       'Position', 'Drafted'],
      dtype='object')

In [ ]:
drop_columns = ['Year', 'Player', 'School', 'Drafted..tm.rnd.yr.', 'Drafted']

In [ ]:
X=nfl_draft.drop(drop_columns, axis=1)

In [ ]:
y=nfl_draft['Drafted']

We need ti decide which features to keep for our model, and which ones to drop

In [ ]:
nfl_not_drafted=nfl_draft[nfl_draft['Drafted']=='No']

In [ ]:
nfl_not_drafted.head()

,Year,Player,Age,School,Height,Weight,Sprint_40yd,Vertical_Jump,Bench_Press_Reps,Broad_Jump,Agility_3cone,Shuttle,Drafted..tm.rnd.yr.,BMI,Player_Type,Position_Type,Position,Drafted
2254,2009,Jahi Word-Daniels\WordJa99,22.0,Georgia Tech,1.8288,89.357697,4.59,90.17,24.0,309.88,NaN,NaN,NaN,26.717729,defense,defensive_back,CB,No
2255,2009,John Parker Wilson\WilsJo01,23.0,Alabama,1.8542,99.336729,4.75,74.93,NaN,266.70,7.53,4.59,NaN,28.893270,offense,backs_receivers,QB,No
2256,2009,Edwin Williams\WillEd02,22.0,Maryland,1.8796,139.706450,5.40,72.39,22.0,251.46,8.15,4.98,NaN,39.544454,offense,offensive_lineman,C,No
2257,2009,Drew Willy\WillDr00,22.0,Buffalo,1.9050,97.522360,4.90,77.47,NaN,276.86,7.18,4.45,NaN,26.872882,offense,backs_receivers,QB,No
2258,2009,Derek Walker\WalkDe98,22.0,Illinois,1.9304,121.562755,4.98,95.25,24.0,292.10,7.31,4.41,NaN,32.621649,defense,defensive_lineman,DE,No

In [ ]:
X['Player_Type'].unique()

array(['offense', 'defense', 'special_teams'], dtype=object)

In [ ]:
X['Position_Type'].unique()

array(['backs_receivers', 'defensive_lineman', 'offensive_lineman',
       'defensive_back', 'line_backer', 'kicking_specialist',
       'other_special'], dtype=object)

In [ ]:
X['Position'].unique()

array(['RB', 'DE', 'OG', 'FS', 'OLB', 'DT', 'OT', 'CB', 'SS', 'TE', 'ILB',
       'C', 'FB', 'WR', 'P', 'K', 'QB', 'LS', 'S', 'DB'], dtype=object)

Decision about the NaN values - we will replace all NaNs with the average for that specfic columns- ['Position']['Position_Type']['Player_Type']

In [ ]:
dummies_needed = ['Position', 'Position_Type', 'Player_Type']

In [ ]:
X = pd.get_dummies(X, columns=dummies_needed, dtype=int)

In [ ]:
X.head()

,Age,Height,Weight,Sprint_40yd,Vertical_Jump,Bench_Press_Reps,Broad_Jump,Agility_3cone,Shuttle,BMI,...,Position_Type_backs_receivers,Position_Type_defensive_back,Position_Type_defensive_lineman,Position_Type_kicking_specialist,Position_Type_line_backer,Position_Type_offensive_lineman,Position_Type_other_special,Player_Type_defense,Player_Type_offense,Player_Type_special_teams
0,20.0,1.8542,106.594207,4.38,85.09,25.0,325.12,NaN,NaN,31.004194,...,1,0,0,0,0,0,0,0,1,0
1,22.0,1.8796,118.387609,4.84,83.82,27.0,292.10,7.38,4.45,33.510073,...,0,0,1,0,0,0,0,1,0,0
2,24.0,2.0066,165.107623,5.50,NaN,21.0,NaN,NaN,NaN,41.005821,...,0,0,0,0,0,1,0,0,1,0
3,23.0,1.8034,92.079251,4.49,93.98,15.0,304.80,7.09,4.23,28.312463,...,0,1,0,0,0,0,0,1,0,0
4,22.0,1.8796,110.676538,4.76,92.71,26.0,304.80,7.10,4.40,31.327425,...,0,0,0,0,1,0,0,1,0,0

In [ ]:
X=X.fillna(X.mean(axis=0))

In [ ]:
X.isna().sum()

Age                                 0
Height                              0
Weight                              0
Sprint_40yd                         0
Vertical_Jump                       0
Bench_Press_Reps                    0
Broad_Jump                          0
Agility_3cone                       0
Shuttle                             0
BMI                                 0
Position_C                          0
Position_CB                         0
Position_DB                         0
Position_DE                         0
Position_DT                         0
Position_FB                         0
Position_FS                         0
Position_ILB                        0
Position_K                          0
Position_LS                         0
Position_OG                         0
Position_OLB                        0
Position_OT                         0
Position_P                          0
Position_QB                         0
Position_RB                         0
Position_S                          0
Position_SS                         0
Position_TE                         0
Position_WR                         0
Position_Type_backs_receivers       0
Position_Type_defensive_back        0
Position_Type_defensive_lineman     0
Position_Type_kicking_specialist    0
Position_Type_line_backer           0
Position_Type_offensive_lineman     0
Position_Type_other_special         0
Player_Type_defense                 0
Player_Type_offense                 0
Player_Type_special_teams           0
dtype: int64

In [ ]:
X.describe()

,Age,Height,Weight,Sprint_40yd,Vertical_Jump,Bench_Press_Reps,Broad_Jump,Agility_3cone,Shuttle,BMI,...,Position_Type_backs_receivers,Position_Type_defensive_back,Position_Type_defensive_lineman,Position_Type_kicking_specialist,Position_Type_line_backer,Position_Type_offensive_lineman,Position_Type_other_special,Player_Type_defense,Player_Type_offense,Player_Type_special_teams
count,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000,...,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000,3477.000000
mean,21.983259,1.873968,109.746393,4.769080,83.392403,20.241058,291.629698,7.237416,4.403843,31.074417,...,0.362381,0.188956,0.144090,0.031924,0.109290,0.159620,0.003739,0.442335,0.522002,0.035663
std,0.889489,0.067494,20.483780,0.293835,9.547962,5.588099,21.304494,0.330709,0.217425,4.438279,...,0.480757,0.391530,0.351231,0.175823,0.312047,0.366306,0.061041,0.496735,0.499588,0.185475
min,18.000000,1.651000,67.585263,4.220000,44.450000,2.000000,198.120000,6.280000,3.810000,21.609798,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,21.000000,1.828800,92.986436,4.540000,78.740000,17.000000,284.480000,7.050000,4.280000,27.475641,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,22.000000,1.879600,104.779837,4.710000,83.392403,20.241058,291.629698,7.237416,4.403843,30.122626,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,22.000000,1.930400,125.645087,4.940000,88.900000,23.000000,304.800000,7.260000,4.450000,34.038647,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
max,28.000000,2.082800,167.375585,6.000000,114.300000,49.000000,373.380000,9.040000,5.560000,44.680097,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
nfl_draft.describe()

,Year,Age,Height,Weight,Sprint_40yd,Vertical_Jump,Bench_Press_Reps,Broad_Jump,Agility_3cone,Shuttle,BMI
count,3477.000000,2927.000000,3477.000000,3477.000000,3303.000000,2780.000000,2572.000000,2749.000000,2260.000000,2337.000000,3477.000000
mean,2013.823699,21.983259,1.873968,109.746393,4.769080,83.392403,20.241058,291.629698,7.237416,4.403843,31.074417
std,3.075616,0.969490,0.067494,20.483780,0.301477,10.678403,6.497600,23.960879,0.410230,0.265224,4.438279
min,2009.000000,18.000000,1.651000,67.585263,4.220000,44.450000,2.000000,198.120000,6.280000,3.810000,21.609798
25%,2011.000000,21.000000,1.828800,92.986436,4.530000,76.200000,15.000000,276.860000,6.940000,4.200000,27.475641
50%,2014.000000,22.000000,1.879600,104.779837,4.690000,83.820000,20.000000,294.640000,7.140000,4.360000,30.122626
75%,2016.000000,23.000000,1.930400,125.645087,4.960000,90.170000,25.000000,307.340000,7.490000,4.560000,34.038647
max,2019.000000,28.000000,2.082800,167.375585,6.000000,114.300000,49.000000,373.380000,9.040000,5.560000,44.680097

In [ ]:
from sklearn import preprocessing
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [ ]:
pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [ ]:
pipe.score(X_test, y_test)

0.7298850574712644

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
pipe2 = make_pipeline(StandardScaler(), DecisionTreeClassifier())
pipe2.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [ ]:
pipe2.score(X_test, y_test)

0.7298850574712644

In [ ]:
from sklearn.ensemble import HistGradientBoostingClassifier

In [ ]:
pipe3 = make_pipeline(StandardScaler(),HistGradientBoostingClassifier())

In [ ]:
pipe3.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('histgradientboostingclassifier',
                 HistGradientBoostingClassifier())])

In [ ]:
pipe3.score(X_test, y_test)

0.8045977011494253

In [ ]:
from xgboost import XGBClassifier

In [ ]:
model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=5,
    random_state=42,
    eval_metric="logloss"
)

In [ ]:
df = pd.read_csv("nfl_draft.csv")

In [ ]:
df["Drafted"] = df["Drafted"].map({"No": 0, "Yes": 1})

X = df.drop("Drafted", axis=1)
y = df["Drafted"]

In [ ]:
df = df.drop(columns=["Player","School","Drafted..tm.rnd.yr.","Player_Type","Position_Type","Position"])

In [ ]:
X = df.drop("Drafted", axis=1)
y = df["Drafted"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [ ]:
model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=5,
    eval_metric="logloss"
)

In [ ]:
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=500, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
predictions = model.predict(X_test)

In [ ]:
accuracy = model.score(X_test, y_test)
print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.8103448275862069

In [ ]:
from sklearn.svm import SVC

In [ ]:
df = pd.read_csv("nfl_draft.csv")

In [ ]:
df["Drafted"] = df["Drafted"].map({"No": 0, "Yes": 1})

In [ ]:
df = df.drop(columns=["Player","School","Drafted..tm.rnd.yr.","Player_Type","Position_Type","Position"])

In [ ]:
X = df.drop("Drafted", axis=1)
y = df["Drafted"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(strategy="mean")

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

In [ ]:
model = SVC(kernel="rbf")

In [ ]:
model.fit(X_train, y_train)

SVC()

In [ ]:
accuracy = model.score(X_test, y_test)

In [ ]:
print("SVC Accuracy:", accuracy)

SVC Accuracy: 0.6738505747126436

In [ ]:
nfl_draft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3477 entries, 0 to 3476
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 3477 non-null   int64
 1   Player               3477 non-null   object
 2   Age                  2927 non-null   float64
 3   School               3477 non-null   object
 4   Height               3477 non-null   float64
 5   Weight               3477 non-null   float64
 6   Sprint_40yd          3303 non-null   float64
 7   Vertical_Jump        2780 non-null   float64
 8   Bench_Press_Reps     2572 non-null   float64
 9   Broad_Jump           2749 non-null   float64
 10  Agility_3cone        2260 non-null   float64
 11  Shuttle              2337 non-null   float64
 12  Drafted..tm.rnd.yr.  2254 non-null   object
 13  BMI                  3477 non-null   float64
 14  Player_Type          3477 non-null   object
 15  Position_Type        3477 non-null   object
 16  Position             3477 non-null   object
 17  Drafted              3477 non-null   object
dtypes: float64(10), int64(1), object(7)
memory usage: 489.1+ KB

# 2. **Preparing the Data**

# 3. **Implementing Logistic regression**

# 4. **Other Models**